using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using Dm.Core.Text;

namespace Dm.Core.Symbols;

/// <summary>
/// Seeds an <see cref="ObjectTree"/> with the BYOND standard library.
/// </summary>
/// <remarks>
/// <para>
/// None of this appears in any source file — <c>mob.Move()</c>, <c>.loc</c> and <c>.client</c> live
/// in <c>byondcore.dll</c> — so without it a completion list shows only what the project itself
/// wrote. The table is generated by <c>tools/builtins-gen</c> from the DM Reference plus
/// <c>stddef.dm</c>, and records the BYOND version it was built from.
/// </para>
/// <para>
/// The format is line-oriented rather than the JSON the plan first named. <c>Dm.Core</c> is a
/// NativeAOT target, so a reflection-based deserializer is not an option and JSON would mean source
/// generators for a fixed, read-only schema. The reader below is a dozen lines, and the file diffs
/// cleanly when a BYOND release moves something.
/// </para>
/// </remarks>
public static class Builtins
{
    private const string ResourceName = "Dm.Core.Resources.builtins.txt";

    /// <summary>The BYOND version the bundled table was generated from.</summary>
    /// <summary>
    /// BYOND version the <b>bundled</b> table was generated from.
    /// </summary>
    /// <remarks>
    /// Set once from the embedded resource and never by a caller's table. It used to be assigned by
    /// every <see cref="Read"/>, which made it global mutable state: a caller supplying its own
    /// table changed the reported version for everything else in the process, and two tests running
    /// in parallel raced over it. A supplied table's version is returned to whoever supplied it.
    /// </remarks>
    public static string Version { get; private set; } = "unknown";

    /// <summary>Builds a tree holding only the builtins.</summary>
    public static ObjectTree CreateTree()
    {
        ObjectTree tree = new();
        Seed(tree);
        return tree;
    }

    /// <summary>Adds the builtins to an existing tree, before any project files.</summary>
    /// <remarks>
    /// Seed first. A project legitimately reopens <c>/mob</c> to add its own members, and the tree
    /// merges the two — so the order only matters in that the builtins must exist for a project
    /// declaration to attach to.
    /// </remarks>
    public static void Seed(ObjectTree tree)
    {
        ArgumentNullException.ThrowIfNull(tree);

        using Stream? stream = typeof(Builtins).GetTypeInfo().Assembly.GetManifestResourceStream(ResourceName);

        if (stream is null)
            return;

        using StreamReader reader = new(stream);

        // The bundled table is the one Version describes, so this is the only assignment.
        Version = Read(tree, reader);
    }

    /// <summary>
    /// Parses a table into a tree and returns the version it declares.
    /// </summary>
    /// <remarks>
    /// Public so a caller can supply a newer table than the bundled copy. The version comes back as
    /// a return value rather than landing in <see cref="Version"/>, which describes the bundled
    /// table alone.
    /// </remarks>
    public static string Read(ObjectTree tree, TextReader reader)
    {
        ArgumentNullException.ThrowIfNull(tree);
        ArgumentNullException.ThrowIfNull(reader);

        string declared = "unknown";

        while (reader.ReadLine() is { } line)
        {
            if (line.Length == 0 || line[0] == '#')
                continue;

            if (line.StartsWith("version ", StringComparison.Ordinal))
            {
                declared = line["version ".Length..].Trim();
                continue;
            }

            // `T <path>` | `V <owner> <name> [type]` | `P <owner> <name> [params]` | `X <type> <parent>`
            string[] parts = line.Split(' ', 4, StringSplitOptions.RemoveEmptyEntries);

            if (parts.Length < 2)
                continue;

            switch (parts[0])
            {
                case "T":
                    MarkBuiltin(tree.GetOrAdd(TypePath.Parse(parts[1])));
                    break;

                case "X" when parts.Length >= 3:
                    tree.GetOrAdd(TypePath.Parse(parts[1])).ParentType = TypePath.Parse(parts[2]);
                    break;

                // `V#` / `P#` mark an entry the DM Reference documents, so its anchor exists.
                case "V" or "V#" when parts.Length >= 3:
                {
                    TypeSymbol owner = MarkBuiltin(tree.GetOrAdd(TypePath.Parse(parts[1])));

                    // The optional fourth column is the var's declared type — `V / world /world` —
                    // which is what lets `world.` resolve through the var and hover say what it is.
                    TypePath? varType = parts.Length >= 4 ? TypePath.Parse(parts[3]) : null;

                    owner.AddVar(new VarSymbol(parts[2], varType, Array.Empty<string>(), default)
                    {
                        IsBuiltin = true,
                        HasReference = parts[0].Length > 1,
                    });
                    break;
                }

                case "P" or "P#" when parts.Length >= 3:
                {
                    TypeSymbol owner = MarkBuiltin(tree.GetOrAdd(TypePath.Parse(parts[1])));
                    ProcSymbol proc = owner.GetOrAddProc(parts[2], isVerb: false);
                    proc.IsBuiltin = true;
                    proc.HasReference = parts[0].Length > 1;

                    if (parts.Length >= 4 && parts[3].Length > 0)
                        proc.SetBuiltinParameters(parts[3].Split(','));

                    break;
                }
            }
        }

        return declared;
    }

    private static TypeSymbol MarkBuiltin(TypeSymbol type)
    {
        type.IsBuiltin = true;
        return type;
    }
}
