using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using Dm.Core.Symbols;
using Dm.Core.Syntax;
using Dm.Core.Text;

namespace Dm.BuiltinsGen;

/// <summary>
/// Builds <c>builtins.txt</c> from a BYOND install.
/// </summary>
/// <remarks>
/// <para>
/// The BYOND standard library exists in two places and neither is complete on its own:
/// </para>
/// <list type="bullet">
/// <item><description><c>help/ref/info.html</c> — everything compiled into <c>byondcore.dll</c>:
/// <c>/atom</c>, <c>/mob</c>, <c>/client</c>, <c>/world</c>, <c>/list</c> and the global procs.
/// None of it appears in any source file, so it can only be scraped.</description></item>
/// <item><description><c>stddef.dm</c> — the constants and wrapper datums Dream Maker compiles
/// ahead of every project. Parsed with our own parser, which doubles as a self-test: it is real
/// BYOND-authored DM full of brace blocks, operator overloads and comma var lists.</description></item>
/// </list>
/// <para>
/// <c>stddef.dm</c> is BYOND-generated output and is not vendored into this repo. Point this tool at
/// a local copy, produced by creating a file named <c>stddef.dm</c> in a project and compiling.
/// </para>
/// </remarks>
internal static class Program
{
    /// <summary>Anchor prefixes that document the language rather than declaring a type.</summary>
    private static readonly HashSet<string> NotTypes = new(StringComparer.Ordinal)
    {
        "DM", "operator", "{skin}", "{notes}", "{{appendix}}",
    };

    private static int Main(string[] args)
    {
        if (args.Length < 2)
        {
            Console.Error.WriteLine("usage: builtins-gen <info.html> <out.txt> [stddef.dm]");
            Console.Error.WriteLine();
            Console.Error.WriteLine("  info.html   from <BYOND>/help/ref/");
            Console.Error.WriteLine("  stddef.dm   optional; generated by compiling a file of that name");
            return 1;
        }

        string referencePath = args[0];
        string outputPath = args[1];
        string? stddefPath = args.Length > 2 ? args[2] : null;

        if (!File.Exists(referencePath))
        {
            Console.Error.WriteLine($"error: no reference at {referencePath}");
            return 1;
        }

        string html = File.ReadAllText(referencePath);
        string version = ReadVersion(html, stddefPath);

        SortedDictionary<string, Entry> entries = new(StringComparer.Ordinal);

        int fromReference = ScrapeReference(html, entries);
        int parents = ScrapeParentTypes(html, entries) + AddVerifiedParentTypes(entries);
        int verifiedMembers = AddVerifiedMembers(entries);
        int fromStddef = stddefPath is not null && File.Exists(stddefPath)
            ? ReadStddef(stddefPath, entries)
            : 0;

        Write(outputPath, version, entries);

        Console.Out.WriteLine($"builtins for BYOND {version}");
        Console.Out.WriteLine(
            $"  {fromReference} from the reference ({parents} parent links), {verifiedMembers} verified members, {fromStddef} from stddef.dm");
        Console.Out.WriteLine($"  {entries.Count} entries -> {outputPath}");

        if (stddefPath is null)
            Console.Out.WriteLine("  note: no stddef.dm given, so constants and wrapper datums are missing");

        return 0;
    }

    private sealed class Entry
    {
        public char Kind;               // T type, V var, P proc, X parent link
        public string Owner = "/";
        public string Name = string.Empty;

        // A proc's parameter list — or, for a var, its declared type (`/world` for the global
        // `world`). Optional in both cases and empty nearly everywhere.
        public string Signature = string.Empty;
    }

    /// <summary>
    /// Scrapes the reference's anchors, which are already written as DM paths.
    /// </summary>
    /// <remarks>
    /// <c>&lt;a name=/mob/var/ckey&gt;</c> and <c>&lt;a name=/mob/proc/Login&gt;</c> carry the same
    /// <c>var</c> and <c>proc</c> segments source code uses, so the split is the one the object tree
    /// already applies rather than anything reference-specific.
    /// </remarks>
    private static int ScrapeReference(string html, SortedDictionary<string, Entry> entries)
    {
        int added = 0;

        foreach (Match match in Regex.Matches(html, @"<a name=(/[^ >]*)[^>]*>"))
        {
            string path = match.Groups[1].Value;
            string[] segments = path.Trim('/').Split('/');

            if (segments.Length == 0 || NotTypes.Contains(segments[0]))
                continue;

            int keyword = Array.FindIndex(segments, s => s is "var" or "proc" or "verb");

            if (keyword < 0)
            {
                // A bare type path, such as `/atom/movable`.
                if (Add(entries, new Entry { Kind = 'T', Owner = "/" + string.Join('/', segments) }))
                    added++;

                continue;
            }

            // The trailing `var`/`proc` with nothing after it is a section heading, not a member.
            if (keyword == segments.Length - 1)
                continue;

            string owner = keyword == 0 ? "/" : "/" + string.Join('/', segments[..keyword]);
            string name = segments[^1];

            if (!IsIdentifier(name))
                continue;

            Entry entry = new()
            {
                Kind = segments[keyword] == "var" ? 'V' : 'P',
                Owner = owner,
                Name = name,
                Signature = segments[keyword] == "var" ? string.Empty : ReadFormat(html, match.Index, name),
            };

            if (Add(entries, entry))
                added++;
        }

        return added;
    }

    /// <summary>
    /// Reads the built-in inheritance links, which the paths do not encode.
    /// </summary>
    /// <remarks>
    /// <c>/mob</c> is a child of the root by path but inherits from <c>/atom/movable</c>, so without
    /// these links <c>mob.</c> would offer nothing from <c>/atom</c> — no <c>loc</c>, no
    /// <c>Move()</c>. The reference states each one in prose: "The default parent_type of /mob is
    /// /atom/movable".
    /// </remarks>
    private static int ScrapeParentTypes(string html, SortedDictionary<string, Entry> entries)
    {
        int added = 0;

        foreach (Match match in Regex.Matches(
            html,
            @"default parent_type of <a href=#(/[^>]+)>[^<]*</a>\s+is\s+<a href=#(/[^>]+)>"))
        {
            Entry entry = new()
            {
                Kind = 'X',
                Owner = match.Groups[1].Value,
                Name = match.Groups[2].Value,
            };

            if (Add(entries, entry))
                added++;
        }

        return added;
    }

    /// <summary>
    /// The inheritance links the reference does not state, read off the compiler.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The reference documents only four in prose — <c>/mob</c>, <c>/obj</c>, <c>/turf</c> and
    /// <c>/area</c>. The rest were read from a running program on 516.1666 by printing
    /// <c>initial(T:parent_type)</c> for each type path, so they are the compiler's own answer
    /// rather than a reconstruction.
    /// </para>
    /// <para>
    /// Two results are not what a reader would guess, which is why they were measured rather than
    /// assumed: <c>/client</c>, <c>/list</c> and <c>/savefile</c> have <b>no parent at all</b>
    /// instead of descending from <c>/datum</c>, and <c>/mutable_appearance</c> descends from
    /// <c>/image</c>. They are absent here because there is no link to record.
    /// </para>
    /// </remarks>
    private static int AddVerifiedParentTypes(SortedDictionary<string, Entry> entries)
    {
        (string Type, string Parent)[] links =
        {
            ("/atom", "/datum"),
            ("/atom/movable", "/atom"),
            ("/mob", "/atom/movable"),
            ("/obj", "/atom/movable"),
            ("/turf", "/atom"),
            ("/area", "/atom"),
            ("/sound", "/datum"),
            ("/icon", "/datum"),
            ("/image", "/datum"),
            ("/matrix", "/datum"),
            ("/regex", "/datum"),
            ("/database", "/datum"),
            ("/exception", "/datum"),
            ("/mutable_appearance", "/image"),

            // Found by diffing this table against `dm.exe -code_tree`, which lists the builtin
            // branches from any project at all, then confirmed the same way as the rest. Missing
            // them meant a `/particles` var offered nothing from /datum - no type, no tag, no New.
            ("/particles", "/datum"),
            ("/dm_filter", "/datum"),
            ("/generator", "/datum"),
        };

        int added = 0;

        foreach ((string type, string parent) in links)
        {
            if (Add(entries, new Entry { Kind = 'X', Owner = type, Name = parent }))
                added++;
        }

        return added;
    }

    /// <summary>
    /// Members the reference does not document, read off the compiler.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The scrape only finds what <c>info.html</c> carries an <c>&lt;a name=...&gt;</c> anchor for, and
    /// for several types it carries almost nothing: <c>/callee</c> had no members at all, and
    /// <c>/image</c> had exactly one. A language server that checks whether a member exists cannot
    /// use a table with holes in it — every hole is reported as the author's mistake.
    /// </para>
    /// <para>
    /// Established by compiling a matrix: every candidate name read into a var off every type, one
    /// file, one compile, and whatever the compiler rejects drops out. Over-guessing the candidate
    /// list is free; under-guessing is what leaves a hole. <b>Each type carries a control name that
    /// must fail</b> — the first version of the probe wrote a bare <c>R.member</c> statement, which
    /// dm.exe does not type-check, so it compiled with 0 errors and proved nothing.
    /// </para>
    /// <para>
    /// Found by /tg/station reporting 97 invented diagnostics, 80-odd of which were these. Verified
    /// on 516.1666. Re-run the probe after a BYOND upgrade, the same as the rest of this file.
    /// </para>
    /// </remarks>
    private static int AddVerifiedMembers(SortedDictionary<string, Entry> entries)
    {
        // /alist is 516's associative list and appears nowhere in this reference version.
        // Compiler-verified: `/alist` resolves as a path, `var/alist/A = new` works with keyed
        // assignment, `initial(t:parent_type)` is empty — parentless, the same as /list — and
        // /tg/station's isalist() family expands to istype(X, /alist). Identical on 516.1686.
        int added = Add(entries, new Entry { Kind = 'T', Owner = "/alist" }) ? 1 : 0;

        Dictionary<string, string[]> members = new()
        {
            ["/alist"] = new[] { "len", "parent_type", "tag", "type", "vars" },
            ["/callee"] = new[] { "args", "caller", "desc", "file", "invisibility", "line", "name", "proc", "src", "type", "usr" },
            ["/client"] = new[] { "bound_height", "bound_width", "bound_x", "bound_y", "parent_type", "tag", "type", "vars" },
            ["/image"] = new[] { "alpha", "animate_movement", "appearance", "appearance_flags", "blend_mode", "color", "contents", "density", "desc", "dir", "filters", "gender", "glide_size", "icon", "icon_state", "infra_luminosity", "invisibility", "layer", "luminosity", "maptext", "maptext_height", "maptext_width", "maptext_x", "maptext_y", "mouse_drag_pointer", "mouse_drop_pointer", "mouse_drop_zone", "mouse_opacity", "mouse_over_pointer", "name", "opacity", "overlays", "override", "pixel_w", "pixel_x", "pixel_y", "pixel_z", "plane", "render_source", "render_target", "screen_loc", "suffix", "text", "transform", "underlays", "verbs", "vis_contents", "x", "y", "z" },
            ["/list"] = new[] { "parent_type", "tag", "type", "vars" },
            ["/mutable_appearance"] = new[] { "animate_movement", "density", "glide_size", "infra_luminosity", "mouse_drop_pointer", "mouse_drop_zone", "opacity", "screen_loc", "verbs", "vis_contents", "vis_flags" },
            ["/savefile"] = new[] { "parent_type", "tag", "type", "vars" },
            ["/world"] = new[] { "vars" },
        };

        // The global `world` is the one builtin GLOBAL a DM program reaches by bare name — one of
        // the most-typed identifiers in the language, and nothing in the reference's anchors
        // declares it. Its type is /world: `var/world/w = world` compiles and `istype(world,
        // /world)` holds. Recorded with the declared type so hover can say what it is.
        if (Add(entries, new Entry { Kind = 'V', Owner = "/", Name = "world", Signature = "/world" }))
            added++;

        foreach ((string owner, string[] names) in members)
        {
            foreach (string name in names)
            {
                if (Add(entries, new Entry { Kind = 'V', Owner = owner, Name = name }))
                    added++;
            }
        }

        // /alist carries /list's whole proc surface: every one of these plus `len` compiles on a
        // typed alist while a control name fails — one file, one compile, 516.1666.
        foreach (string name in new[]
                 { "Add", "Copy", "Cut", "Find", "Insert", "Join", "Remove", "RemoveAll", "Splice", "Swap" })
        {
            if (Add(entries, new Entry { Kind = 'P', Owner = "/alist", Name = name }))
                added++;
        }

        return added;
    }

    /// <summary>
    /// Rejects anchor names that are not DM identifiers.
    /// </summary>
    /// <remarks>
    /// The reference percent-encodes punctuation into its anchors, so <c>/proc/.</c> arrives as
    /// <c>%2e</c>. Those are documentation targets for operators rather than declarations.
    /// </remarks>
    private static bool IsIdentifier(string name)
    {
        if (name.Length == 0)
            return false;

        foreach (char c in name)
        {
            if (!char.IsLetterOrDigit(c) && c != '_' && c != '\\')
                return false;
        }

        return !char.IsDigit(name[0]);
    }

    /// <summary>
    /// Pulls a proc's parameter list out of the <c>Format:</c> block that follows its anchor.
    /// </summary>
    /// <remarks>
    /// The reference prints one or more call shapes, as in <c>istype(Val,Type)</c>. The first that
    /// names this proc is taken; the rest are overloads the object tree has no way to express.
    /// </remarks>
    private static string ReadFormat(string html, int anchorIndex, string name)
    {
        // Stay inside this entry: the next anchor begins the next one.
        int next = html.IndexOf("<a name=", anchorIndex + 1, StringComparison.Ordinal);
        int end = next < 0 ? html.Length : next;

        int format = html.IndexOf("<b>Format:</b>", anchorIndex, StringComparison.Ordinal);
        if (format < 0 || format > end)
            return string.Empty;

        Match call = Regex.Match(
            html[format..Math.Min(end, format + 600)],
            Regex.Escape(name) + @"\s*\(([^)]*)\)");

        if (!call.Success)
            return string.Empty;

        // Strip markup and whitespace; keep the parameter names as written.
        string parameters = Regex.Replace(call.Groups[1].Value, "<[^>]*>", string.Empty);
        return Regex.Replace(parameters, @"\s+", string.Empty);
    }

    /// <summary>Parses <c>stddef.dm</c> with our own parser and takes what it declares.</summary>
    private static int ReadStddef(string path, SortedDictionary<string, Entry> entries)
    {
        SourceText text = SourceText.From(File.ReadAllText(path), path);
        ParseResult parse = DeclarationParser.Parse(Lexer.Lex(text));

        if (parse.Diagnostics.Count > 0)
        {
            // Worth surfacing: stddef.dm is BYOND's own DM, so a diagnostic here is our bug.
            Console.Error.WriteLine($"warning: {parse.Diagnostics.Count} diagnostic(s) parsing stddef.dm");

            foreach (Dm.Core.Diagnostics.Diagnostic diagnostic in parse.Diagnostics)
            {
                LinePosition at = text.GetLinePosition(diagnostic.Span.Start);
                Console.Error.WriteLine($"  {at.Line + 1}:{at.Character + 1}  {diagnostic.Id} {diagnostic.Message}");
            }
        }

        ObjectTree tree = new();
        TypeTreeBuilder.AddFile(tree, path, parse);

        int added = 0;

        foreach (TypeSymbol type in tree.Types)
        {
            if (type.Path.IsRoot)
                continue;

            if (type.IsDeclared && Add(entries, new Entry { Kind = 'T', Owner = type.Path.Text }))
                added++;

            foreach (VarSymbol variable in type.Vars)
            {
                if (Add(entries, new Entry { Kind = 'V', Owner = type.Path.Text, Name = variable.Name }))
                    added++;
            }

            foreach (ProcSymbol proc in type.Procs)
            {
                Entry entry = new()
                {
                    Kind = 'P',
                    Owner = type.Path.Text,
                    Name = proc.Name,
                    Signature = string.Join(',', proc.Parameters),
                };

                if (Add(entries, entry))
                    added++;
            }
        }

        return added;
    }

    private static bool Add(SortedDictionary<string, Entry> entries, Entry entry)
    {
        string key = $"{entry.Kind}{entry.Owner} {entry.Name}";

        if (entries.ContainsKey(key))
            return false;

        entries.Add(key, entry);
        return true;
    }

    private static string ReadVersion(string html, string? stddefPath)
    {
        if (stddefPath is not null && File.Exists(stddefPath))
        {
            Match stamped = Regex.Match(File.ReadAllText(stddefPath), @"Version\s+(\d+\.\d+)");
            if (stamped.Success)
                return stamped.Groups[1].Value;
        }

        Match fromHtml = Regex.Match(html, @"[Vv]ersion\s+(\d{3}\.\d+)");
        return fromHtml.Success ? fromHtml.Groups[1].Value : "unknown";
    }

    /// <summary>
    /// Writes the table.
    /// </summary>
    /// <remarks>
    /// A line-oriented text file rather than the JSON the plan first called for. <c>Dm.Core</c> is a
    /// NativeAOT target, so a reflection-based deserializer is not an option and JSON would mean
    /// source generators for a fixed, read-only schema. This format needs a dozen lines to read, and
    /// it diffs cleanly when a BYOND release moves something.
    /// </remarks>
    private static void Write(string path, string version, SortedDictionary<string, Entry> entries)
    {
        StringBuilder output = new();
        output.Append("# BYOND builtins, generated by tools/builtins-gen. Do not edit by hand.\n");
        output.Append("# T <path> | V <owner> <name> [type] | P <owner> <name> [params]\n");
        output.Append($"version {version}\n");

        foreach (Entry entry in entries.Values)
        {
            switch (entry.Kind)
            {
                case 'T':
                    output.Append("T ").Append(entry.Owner).Append('\n');
                    break;

                case 'V':
                    output.Append("V ").Append(entry.Owner).Append(' ').Append(entry.Name);

                    if (entry.Signature.Length > 0)
                        output.Append(' ').Append(entry.Signature);

                    output.Append('\n');
                    break;

                case 'X':
                    output.Append("X ").Append(entry.Owner).Append(' ').Append(entry.Name).Append('\n');
                    break;

                default:
                    output.Append("P ").Append(entry.Owner).Append(' ').Append(entry.Name);

                    if (entry.Signature.Length > 0)
                        output.Append(' ').Append(entry.Signature);

                    output.Append('\n');
                    break;
            }
        }

        Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(path))!);
        File.WriteAllText(path, output.ToString());
    }
}
