// Smoke test for the dm_core C ABI.
//
// Purpose is twofold: verify the boundary works from C++, and serve as the reference
// integration for the Qt client. If this passes and a client still misbehaves, the bug is
// in the client.
//
// Covers the three things that are expensive to get wrong later: version negotiation,
// string ownership, and handle lifetime including use-after-close.

#include "dm_core.h"

#include <cstdio>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <string>

namespace fs = std::filesystem;

static int g_failures = 0;

static void check(bool condition, const char *what)
{
    std::printf("  [%s] %s\n", condition ? "ok" : "FAIL", what);
    if (!condition)
        ++g_failures;
}

// Reads and frees a string owned by the library.
static std::string take(char *owned)
{
    if (owned == nullptr)
        return std::string();

    std::string copy(owned);
    dm_free(owned);
    return copy;
}

static void test_version()
{
    std::printf("version\n");

    const int32_t version = dm_abi_version();
    std::printf("  reported %d.%d\n", DM_ABI_VERSION_MAJOR(version), DM_ABI_VERSION_MINOR(version));

    check(DM_ABI_VERSION_MAJOR(version) == DM_ABI_EXPECTED_MAJOR,
          "major version matches the header this client was built against");
}

static void test_open_missing()
{
    std::printf("open a .dme that does not exist\n");

    dm_workspace ws = nullptr;
    const dm_status status = dm_workspace_open("this-file-does-not-exist.dme", &ws);

    check(status == DM_ERR_NOT_FOUND, "returns DM_ERR_NOT_FOUND");
    check(ws == nullptr, "out-parameter is cleared even on failure");

    const std::string message = take(dm_last_error());
    check(!message.empty(), "dm_last_error reports a message");
    std::printf("  message: %s\n", message.c_str());
}

static void test_open_null_out()
{
    std::printf("open with a null out-parameter\n");
    check(dm_workspace_open("whatever.dme", nullptr) == DM_ERR_INVALID_ARG,
          "returns DM_ERR_INVALID_ARG instead of crashing");
}

static void test_lifecycle(const fs::path &dme)
{
    std::printf("workspace lifecycle\n");

    dm_workspace ws = nullptr;
    const dm_status status = dm_workspace_open(dme.string().c_str(), &ws);

    check(status == DM_OK, "open succeeds");
    check(ws != nullptr, "handle is non-null");

    if (status != DM_OK)
        return;

    char *root = nullptr;
    check(dm_workspace_root(ws, &root) == DM_OK, "root query succeeds");

    const std::string root_path = take(root);
    check(!root_path.empty(), "root is a non-empty string");
    std::printf("  root: %s\n", root_path.c_str());

    check(fs::equivalent(fs::path(root_path), dme.parent_path()),
          "root is the directory containing the .dme");

    dm_workspace_close(ws);

    // The handle is now stale. A client bug that reuses it must produce a clean error, not
    // a resolved-but-wrong object and not a crash.
    char *after = reinterpret_cast<char *>(0x1);
    check(dm_workspace_root(ws, &after) == DM_ERR_INVALID_HANDLE,
          "using a closed handle returns DM_ERR_INVALID_HANDLE");
    check(after == nullptr, "out-parameter is cleared on the stale-handle path");

    dm_workspace_close(ws);
    check(true, "closing twice does not crash");
}

static void test_free_null()
{
    std::printf("dm_free(nullptr)\n");
    dm_free(nullptr);
    check(true, "accepted");
}

int main()
{
    const fs::path dir = fs::temp_directory_path() / "dm_abi_smoke";
    fs::create_directories(dir);

    const fs::path dme = dir / "smoke.dme";
    {
        std::ofstream out(dme);
        out << "// generated by dm_abi_smoke\n#include \"smoke.dm\"\n";
    }

    std::printf("dm_core ABI smoke test\n\n");

    test_version();
    test_open_missing();
    test_open_null_out();
    test_lifecycle(dme);
    test_free_null();

    std::error_code ignored;
    fs::remove_all(dir, ignored);

    std::printf("\n%s\n", g_failures == 0 ? "all checks passed" : "FAILURES PRESENT");
    return g_failures == 0 ? 0 : 1;
}
